# USER ACCOUNT
#=================================================================

### Register an user with "USER" default role
# Nota : In dev context, need stmp-dev running (smtp server simulation)
# Run, as administrator (sudo in linux), smtp-dev/Rnwood.Smtp4dev binary
# from Inote root project
# Simulated Inbox mail is accessible at :
# http://localhost:5000
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "pseudo":"asterix",
    "username":"obelix@kame-house.com",
    "password":"ssFF@@787$"
}

#### Account activation
# Nota : Pick the activation code in Validation table
# or open fictionous mail box http://localhost:5000 (smtp-dev must be running)
POST http://localhost:8080/api/auth/activation HTTP/1.1
Content-Type: application/json

{
    "code":"778255"
}

#### User sign in
POST http://localhost:8080/api/auth/sign_in HTTP/1.1
# Nota : keep the Bearer, it must be in headers of all secured endpoints
Content-Type: application/json

{
  "username":"obelix@kame-house.com",
  "password":"ssFF@@787$"
}

### User sign out
# Nota : Don't forget to set the good bearer given by server when sign in
POST http://localhost:8080/api/auth/sign_out HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiYXN0ZXJpeCIsImV4cCI6MTcxNjgyNzE1Miwic3ViIjoib2JlbGl4QGthbWUtaG91c2UuY29tIn0.pD-o31fe5sZSUi1OySwX1mzv1JFxAFvmOag5jWjh9j8

### Change password request
# Nota : Don't forget to recuperate activation code
POST http://localhost:8080/api/auth/change_password HTTP/1.1
Content-Type: application/json

{
    "email":"sangoku@kame-house.com"
}

### Send a new password
# Nota: Don't forget to set the good activation code
POST http://localhost:8080/api/auth/new_password HTTP/1.1
Content-Type: application/json

{
    "email":"sangoku@kame-house.com",
    "code":"782725",
    "password": "chichi@@YYY14646_"
}


### Send refresh-token
# Nota : Don't forget to set the good refresh UUID, sended when sign in
POST http://localhost:8080/api/auth/refresh_token HTTP/1.1
Content-Type: application/json

{
   "refresh":"61ff6d18-607c-4220-8a38-1392ff89aec8"
}

### Get current user
# Nota : Don't forget to set the good refresh UUID, sended when sign in
GET http://localhost:8080/api/auth/current-user HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTYxNDIwOTcsInN1YiI6Im9iZWxpeEBrYW1lLWhvdXNlLmNvbSIsIm5hbWUiOiJhc3Rlcml4In0.GlS1VZOfZ7p6_qOXuKrMs2urdnvFwcKsiPn5RaLxURM



#COMMENTS
#========================================================================
### Send a comment
#Nota : dont forget to set the good bearer
POST http://localhost:8080/api/comment/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYW5nb2t1QGthbWUtaG91c2UuY29tIiwibmFtZSI6InNhbmdva3UiLCJleHAiOjE3MTMwMjg5NTd9.u-AV2Q1k5cm49EkX9-SJMFyvBa9stZzA0uw77ksspbo
Content-Type: application/json

{
    "msg": "Hello"
}

### Read All comments
#Don't forget to set the good bearer
GET http://localhost:8080/api/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYW5nb2t1QGthbWUtaG91c2UuY29tIiwibmFtZSI6InNhbmdva3UiLCJleHAiOjE3MTMwMjg5NTd9.u-AV2Q1k5cm49EkX9-SJMFyvBa9stZzA0uw77ksspbo

