# name: Publish JAR to VPS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   publish-jar:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Java
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'temurin'
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           port: ${{ secrets.PORT }}
#           key: ${{ secrets.SSHKEY }}
          
#       - name: create JAR
#         run: mvn clean package
       
#       - name: executing remote ssh commands using password
#         uses: appleboy/ssh-action@master
#         with: 
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           port: ${{ secrets.PORT }}
#           key: ${{ secrets.SSHKEY }}
#           script: mvn spring-boot:run

name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        uses: actions/ssh-deploy@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          path: ${{ secrets.PATH }}
