# name: Deploy

# on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v1
#     - name: Copy repository contents via scp
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         port: ${{ secrets.PORT }}
#         key: ${{ secrets.SSHKEY }}
#         source: "."
#         target: ${{ secrets.PATH }}

#     - name: Set up Java for publishing
#       uses: actions/setup-java@v4
#       with:
#           java-version: '17'
#           distribution: 'temurin'

#     - name: Build with Maven
#       run: mvn -B package --file pom.xml

name: Publish JAR to VPS

on:
  push:
    branches:
      - main

jobs:
  publish-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          
      - name: create JAR
        run: mvn clean package
       
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with: 
          # host: ${{ secrets.HOST }}
          # username: ${{ secrets.USERNAME }}
          # key: ${{ secrets.KEY }}
          # key_path: ${{ secrets.KEY_PATH }}
          # password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: mvn spring-boot:run

      # - name: Run Api
      #   run: mvn spring-boot:run


  
