name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "."
        target: ${{ secrets.PATH }}

    - name: Set PATH
      run: |
          export PATH=$PATH:/usr/bin

    - name: Build jar
      run: |
        bash -c "echo '$PWD'"
  
