# CI/CD pipeline for Inote API
# atsuhikoMochizuki
# 28/04/2024

name: CI/CD pipeline for Inote API

on:
  push:
    branches: ["main"]
jobs:
  # kill-process:
  #   name: kill process
  #   runs-on: ubuntu-latest
  #   steps:
  #    - name: Stop process running on port 8080
  #      uses: appleboy/ssh-action@v1.0.0
  #      with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key: ${{ secrets.SSHKEY }}
  #       port: ${{ secrets.PORT }}
  #       script: fuser -k 8080/tcp

  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
     - name: Create folder on host for jar deployment 
       uses: appleboy/ssh-action@v1.0.0
       with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: mkdir -p ./Inote_project/
  
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
    
    - name: Clone repository on Github Docker container
      uses: actions/checkout@v3

    - name: Load HOST in application.properties
      run: sed -i 's/<front_url>/${{ secrets.FRONT_HOSTNAME }}/g' src/main/resources/application.properties
    
    - name: Load BACKEND_MAIL_DO_NOT_REPLY_ADDRESS in application.properties
      run: sed -i 's/<back_mail_do_not_reply_adress>/${{ secrets.BACKEND_MAIL_DO_NOT_REPLY_ADDRESS }}/g' src/main/resources/application.properties
        
    - name: Set up JDK 17 on Github Docker container
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Package Jar with Maven
      run: mvn -B package --file pom.xml
    
    - name: Rename jar for deployement
      run: mv target/*.jar target/Inote_API.jar
    
    - name: Deploy jar on server via ssh password
      uses: appleboy/scp-action@v0.1.7
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        source: "target/Inote_API.jar"
        target: "./Inote_project/" 
        strip_components: 1

  # reboot: # RestApi will be launch at startup
  #   name: Reboot system (for launching api)
  #   needs: build-and-deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create folder on host for jar deployment 
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.SSHKEY }}
  #         port: ${{ secrets.PORT }}
  #         script: sudo reboot
  
  
  # run-jar: # Never end on github action
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Run jar on server
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.SSHKEY }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #           java -jar ./Inote_project/Inote_API.jar 
      